[features]
seeds = false
skip-lint = false

[programs.devnet]
solana_portal = "A8g3YSrKeLWfPmV6CnrQov4qrb6uH7A3V6pcyuuBVkLc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/kevin/.config/solana/id.json"

[scripts]
test = "node tests/solana-portal.js"
